/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as WallpapersRouteImport } from './routes/wallpapers'
import { Route as StickersRouteImport } from './routes/stickers'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NewsRouteImport } from './routes/news'
import { Route as NailongVsBomboongRouteImport } from './routes/nailong-vs-bomboong'
import { Route as MyCollectionRouteImport } from './routes/my-collection'
import { Route as MemesRouteImport } from './routes/memes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WatchEpisodeIdRouteImport } from './routes/watch.$episodeId'
import { Route as ShopProductIdRouteImport } from './routes/shop.$productId'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as CommunityPostIdRouteImport } from './routes/community.$postId'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminShopIndexRouteImport } from './routes/admin.shop.index'
import { Route as AdminNewsIndexRouteImport } from './routes/admin.news.index'
import { Route as AdminEventsIndexRouteImport } from './routes/admin.events.index'
import { Route as AdminContentIndexRouteImport } from './routes/admin.content.index'
import { Route as AdminCharactersIndexRouteImport } from './routes/admin.characters.index'
import { Route as AdminShopNewRouteImport } from './routes/admin.shop.new'
import { Route as AdminShopProductIdRouteImport } from './routes/admin.shop.$productId'
import { Route as AdminNewsNewRouteImport } from './routes/admin.news.new'
import { Route as AdminNewsNewsSlugRouteImport } from './routes/admin.news.$newsSlug'
import { Route as AdminEventsNewRouteImport } from './routes/admin.events.new'
import { Route as AdminEventsEventIdRouteImport } from './routes/admin.events.$eventId'
import { Route as AdminCharactersNewRouteImport } from './routes/admin.characters.new'
import { Route as AdminCharactersCharIdRouteImport } from './routes/admin.characters.$charId'
import { Route as AdminContentMemesNewRouteImport } from './routes/admin.content.memes.new'
import { Route as AdminContentMemesIdRouteImport } from './routes/admin.content.memes.$id'
import { Route as AdminContentGalleryNewRouteImport } from './routes/admin.content.gallery.new'
import { Route as AdminContentGalleryIdRouteImport } from './routes/admin.content.gallery.$id'
import { Route as AdminContentEpisodesNewRouteImport } from './routes/admin.content.episodes.new'
import { Route as AdminContentEpisodesIdRouteImport } from './routes/admin.content.episodes.$id'

const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const WallpapersRoute = WallpapersRouteImport.update({
  id: '/wallpapers',
  path: '/wallpapers',
  getParentRoute: () => rootRouteImport,
} as any)
const StickersRoute = StickersRouteImport.update({
  id: '/stickers',
  path: '/stickers',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const NailongVsBomboongRoute = NailongVsBomboongRouteImport.update({
  id: '/nailong-vs-bomboong',
  path: '/nailong-vs-bomboong',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCollectionRoute = MyCollectionRouteImport.update({
  id: '/my-collection',
  path: '/my-collection',
  getParentRoute: () => rootRouteImport,
} as any)
const MemesRoute = MemesRouteImport.update({
  id: '/memes',
  path: '/memes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WatchEpisodeIdRoute = WatchEpisodeIdRouteImport.update({
  id: '/$episodeId',
  path: '/$episodeId',
  getParentRoute: () => WatchRoute,
} as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ShopRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const CommunityPostIdRoute = CommunityPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => CommunityRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShopIndexRoute = AdminShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsIndexRoute = AdminNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentIndexRoute = AdminContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCharactersIndexRoute = AdminCharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShopNewRoute = AdminShopNewRouteImport.update({
  id: '/shop/new',
  path: '/shop/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShopProductIdRoute = AdminShopProductIdRouteImport.update({
  id: '/shop/$productId',
  path: '/shop/$productId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsNewRoute = AdminNewsNewRouteImport.update({
  id: '/news/new',
  path: '/news/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsNewsSlugRoute = AdminNewsNewsSlugRouteImport.update({
  id: '/news/$newsSlug',
  path: '/news/$newsSlug',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsNewRoute = AdminEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsEventIdRoute = AdminEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCharactersNewRoute = AdminCharactersNewRouteImport.update({
  id: '/characters/new',
  path: '/characters/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCharactersCharIdRoute = AdminCharactersCharIdRouteImport.update({
  id: '/characters/$charId',
  path: '/characters/$charId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentMemesNewRoute = AdminContentMemesNewRouteImport.update({
  id: '/content/memes/new',
  path: '/content/memes/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentMemesIdRoute = AdminContentMemesIdRouteImport.update({
  id: '/content/memes/$id',
  path: '/content/memes/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentGalleryNewRoute = AdminContentGalleryNewRouteImport.update({
  id: '/content/gallery/new',
  path: '/content/gallery/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentGalleryIdRoute = AdminContentGalleryIdRouteImport.update({
  id: '/content/gallery/$id',
  path: '/content/gallery/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentEpisodesNewRoute = AdminContentEpisodesNewRouteImport.update({
  id: '/content/episodes/new',
  path: '/content/episodes/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentEpisodesIdRoute = AdminContentEpisodesIdRouteImport.update({
  id: '/content/episodes/$id',
  path: '/content/episodes/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/characters': typeof CharactersRoute
  '/community': typeof CommunityRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/memes': typeof MemesRoute
  '/my-collection': typeof MyCollectionRoute
  '/nailong-vs-bomboong': typeof NailongVsBomboongRoute
  '/news': typeof NewsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/shop': typeof ShopRouteWithChildren
  '/stickers': typeof StickersRoute
  '/wallpapers': typeof WallpapersRoute
  '/watch': typeof WatchRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/watch/$episodeId': typeof WatchEpisodeIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/characters/$charId': typeof AdminCharactersCharIdRoute
  '/admin/characters/new': typeof AdminCharactersNewRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/news/$newsSlug': typeof AdminNewsNewsSlugRoute
  '/admin/news/new': typeof AdminNewsNewRoute
  '/admin/shop/$productId': typeof AdminShopProductIdRoute
  '/admin/shop/new': typeof AdminShopNewRoute
  '/admin/characters/': typeof AdminCharactersIndexRoute
  '/admin/content/': typeof AdminContentIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/news/': typeof AdminNewsIndexRoute
  '/admin/shop/': typeof AdminShopIndexRoute
  '/admin/content/episodes/$id': typeof AdminContentEpisodesIdRoute
  '/admin/content/episodes/new': typeof AdminContentEpisodesNewRoute
  '/admin/content/gallery/$id': typeof AdminContentGalleryIdRoute
  '/admin/content/gallery/new': typeof AdminContentGalleryNewRoute
  '/admin/content/memes/$id': typeof AdminContentMemesIdRoute
  '/admin/content/memes/new': typeof AdminContentMemesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/characters': typeof CharactersRoute
  '/community': typeof CommunityRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/memes': typeof MemesRoute
  '/my-collection': typeof MyCollectionRoute
  '/nailong-vs-bomboong': typeof NailongVsBomboongRoute
  '/news': typeof NewsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/shop': typeof ShopRouteWithChildren
  '/stickers': typeof StickersRoute
  '/wallpapers': typeof WallpapersRoute
  '/watch': typeof WatchRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/watch/$episodeId': typeof WatchEpisodeIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/characters/$charId': typeof AdminCharactersCharIdRoute
  '/admin/characters/new': typeof AdminCharactersNewRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/news/$newsSlug': typeof AdminNewsNewsSlugRoute
  '/admin/news/new': typeof AdminNewsNewRoute
  '/admin/shop/$productId': typeof AdminShopProductIdRoute
  '/admin/shop/new': typeof AdminShopNewRoute
  '/admin/characters': typeof AdminCharactersIndexRoute
  '/admin/content': typeof AdminContentIndexRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/admin/news': typeof AdminNewsIndexRoute
  '/admin/shop': typeof AdminShopIndexRoute
  '/admin/content/episodes/$id': typeof AdminContentEpisodesIdRoute
  '/admin/content/episodes/new': typeof AdminContentEpisodesNewRoute
  '/admin/content/gallery/$id': typeof AdminContentGalleryIdRoute
  '/admin/content/gallery/new': typeof AdminContentGalleryNewRoute
  '/admin/content/memes/$id': typeof AdminContentMemesIdRoute
  '/admin/content/memes/new': typeof AdminContentMemesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/characters': typeof CharactersRoute
  '/community': typeof CommunityRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/memes': typeof MemesRoute
  '/my-collection': typeof MyCollectionRoute
  '/nailong-vs-bomboong': typeof NailongVsBomboongRoute
  '/news': typeof NewsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/shop': typeof ShopRouteWithChildren
  '/stickers': typeof StickersRoute
  '/wallpapers': typeof WallpapersRoute
  '/watch': typeof WatchRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/watch/$episodeId': typeof WatchEpisodeIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/characters/$charId': typeof AdminCharactersCharIdRoute
  '/admin/characters/new': typeof AdminCharactersNewRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/news/$newsSlug': typeof AdminNewsNewsSlugRoute
  '/admin/news/new': typeof AdminNewsNewRoute
  '/admin/shop/$productId': typeof AdminShopProductIdRoute
  '/admin/shop/new': typeof AdminShopNewRoute
  '/admin/characters/': typeof AdminCharactersIndexRoute
  '/admin/content/': typeof AdminContentIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/news/': typeof AdminNewsIndexRoute
  '/admin/shop/': typeof AdminShopIndexRoute
  '/admin/content/episodes/$id': typeof AdminContentEpisodesIdRoute
  '/admin/content/episodes/new': typeof AdminContentEpisodesNewRoute
  '/admin/content/gallery/$id': typeof AdminContentGalleryIdRoute
  '/admin/content/gallery/new': typeof AdminContentGalleryNewRoute
  '/admin/content/memes/$id': typeof AdminContentMemesIdRoute
  '/admin/content/memes/new': typeof AdminContentMemesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/characters'
    | '/community'
    | '/contact'
    | '/events'
    | '/faq'
    | '/forgot-password'
    | '/gallery'
    | '/leaderboard'
    | '/login'
    | '/memes'
    | '/my-collection'
    | '/nailong-vs-bomboong'
    | '/news'
    | '/profile'
    | '/register'
    | '/shop'
    | '/stickers'
    | '/wallpapers'
    | '/watch'
    | '/admin/categories'
    | '/admin/moderation'
    | '/admin/settings'
    | '/community/$postId'
    | '/news/$slug'
    | '/shop/$productId'
    | '/watch/$episodeId'
    | '/admin/'
    | '/admin/characters/$charId'
    | '/admin/characters/new'
    | '/admin/events/$eventId'
    | '/admin/events/new'
    | '/admin/news/$newsSlug'
    | '/admin/news/new'
    | '/admin/shop/$productId'
    | '/admin/shop/new'
    | '/admin/characters/'
    | '/admin/content/'
    | '/admin/events/'
    | '/admin/news/'
    | '/admin/shop/'
    | '/admin/content/episodes/$id'
    | '/admin/content/episodes/new'
    | '/admin/content/gallery/$id'
    | '/admin/content/gallery/new'
    | '/admin/content/memes/$id'
    | '/admin/content/memes/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/characters'
    | '/community'
    | '/contact'
    | '/events'
    | '/faq'
    | '/forgot-password'
    | '/gallery'
    | '/leaderboard'
    | '/login'
    | '/memes'
    | '/my-collection'
    | '/nailong-vs-bomboong'
    | '/news'
    | '/profile'
    | '/register'
    | '/shop'
    | '/stickers'
    | '/wallpapers'
    | '/watch'
    | '/admin/categories'
    | '/admin/moderation'
    | '/admin/settings'
    | '/community/$postId'
    | '/news/$slug'
    | '/shop/$productId'
    | '/watch/$episodeId'
    | '/admin'
    | '/admin/characters/$charId'
    | '/admin/characters/new'
    | '/admin/events/$eventId'
    | '/admin/events/new'
    | '/admin/news/$newsSlug'
    | '/admin/news/new'
    | '/admin/shop/$productId'
    | '/admin/shop/new'
    | '/admin/characters'
    | '/admin/content'
    | '/admin/events'
    | '/admin/news'
    | '/admin/shop'
    | '/admin/content/episodes/$id'
    | '/admin/content/episodes/new'
    | '/admin/content/gallery/$id'
    | '/admin/content/gallery/new'
    | '/admin/content/memes/$id'
    | '/admin/content/memes/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/characters'
    | '/community'
    | '/contact'
    | '/events'
    | '/faq'
    | '/forgot-password'
    | '/gallery'
    | '/leaderboard'
    | '/login'
    | '/memes'
    | '/my-collection'
    | '/nailong-vs-bomboong'
    | '/news'
    | '/profile'
    | '/register'
    | '/shop'
    | '/stickers'
    | '/wallpapers'
    | '/watch'
    | '/admin/categories'
    | '/admin/moderation'
    | '/admin/settings'
    | '/community/$postId'
    | '/news/$slug'
    | '/shop/$productId'
    | '/watch/$episodeId'
    | '/admin/'
    | '/admin/characters/$charId'
    | '/admin/characters/new'
    | '/admin/events/$eventId'
    | '/admin/events/new'
    | '/admin/news/$newsSlug'
    | '/admin/news/new'
    | '/admin/shop/$productId'
    | '/admin/shop/new'
    | '/admin/characters/'
    | '/admin/content/'
    | '/admin/events/'
    | '/admin/news/'
    | '/admin/shop/'
    | '/admin/content/episodes/$id'
    | '/admin/content/episodes/new'
    | '/admin/content/gallery/$id'
    | '/admin/content/gallery/new'
    | '/admin/content/memes/$id'
    | '/admin/content/memes/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CharactersRoute: typeof CharactersRoute
  CommunityRoute: typeof CommunityRouteWithChildren
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GalleryRoute: typeof GalleryRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MemesRoute: typeof MemesRoute
  MyCollectionRoute: typeof MyCollectionRoute
  NailongVsBomboongRoute: typeof NailongVsBomboongRoute
  NewsRoute: typeof NewsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ShopRoute: typeof ShopRouteWithChildren
  StickersRoute: typeof StickersRoute
  WallpapersRoute: typeof WallpapersRoute
  WatchRoute: typeof WatchRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallpapers': {
      id: '/wallpapers'
      path: '/wallpapers'
      fullPath: '/wallpapers'
      preLoaderRoute: typeof WallpapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stickers': {
      id: '/stickers'
      path: '/stickers'
      fullPath: '/stickers'
      preLoaderRoute: typeof StickersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nailong-vs-bomboong': {
      id: '/nailong-vs-bomboong'
      path: '/nailong-vs-bomboong'
      fullPath: '/nailong-vs-bomboong'
      preLoaderRoute: typeof NailongVsBomboongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-collection': {
      id: '/my-collection'
      path: '/my-collection'
      fullPath: '/my-collection'
      preLoaderRoute: typeof MyCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memes': {
      id: '/memes'
      path: '/memes'
      fullPath: '/memes'
      preLoaderRoute: typeof MemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/watch/$episodeId': {
      id: '/watch/$episodeId'
      path: '/$episodeId'
      fullPath: '/watch/$episodeId'
      preLoaderRoute: typeof WatchEpisodeIdRouteImport
      parentRoute: typeof WatchRoute
    }
    '/shop/$productId': {
      id: '/shop/$productId'
      path: '/$productId'
      fullPath: '/shop/$productId'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/community/$postId': {
      id: '/community/$postId'
      path: '/$postId'
      fullPath: '/community/$postId'
      preLoaderRoute: typeof CommunityPostIdRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shop/': {
      id: '/admin/shop/'
      path: '/shop'
      fullPath: '/admin/shop/'
      preLoaderRoute: typeof AdminShopIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news/': {
      id: '/admin/news/'
      path: '/news'
      fullPath: '/admin/news/'
      preLoaderRoute: typeof AdminNewsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/': {
      id: '/admin/content/'
      path: '/content'
      fullPath: '/admin/content/'
      preLoaderRoute: typeof AdminContentIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/characters/': {
      id: '/admin/characters/'
      path: '/characters'
      fullPath: '/admin/characters/'
      preLoaderRoute: typeof AdminCharactersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shop/new': {
      id: '/admin/shop/new'
      path: '/shop/new'
      fullPath: '/admin/shop/new'
      preLoaderRoute: typeof AdminShopNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shop/$productId': {
      id: '/admin/shop/$productId'
      path: '/shop/$productId'
      fullPath: '/admin/shop/$productId'
      preLoaderRoute: typeof AdminShopProductIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news/new': {
      id: '/admin/news/new'
      path: '/news/new'
      fullPath: '/admin/news/new'
      preLoaderRoute: typeof AdminNewsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news/$newsSlug': {
      id: '/admin/news/$newsSlug'
      path: '/news/$newsSlug'
      fullPath: '/admin/news/$newsSlug'
      preLoaderRoute: typeof AdminNewsNewsSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/new': {
      id: '/admin/events/new'
      path: '/events/new'
      fullPath: '/admin/events/new'
      preLoaderRoute: typeof AdminEventsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/$eventId': {
      id: '/admin/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/admin/events/$eventId'
      preLoaderRoute: typeof AdminEventsEventIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/characters/new': {
      id: '/admin/characters/new'
      path: '/characters/new'
      fullPath: '/admin/characters/new'
      preLoaderRoute: typeof AdminCharactersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/characters/$charId': {
      id: '/admin/characters/$charId'
      path: '/characters/$charId'
      fullPath: '/admin/characters/$charId'
      preLoaderRoute: typeof AdminCharactersCharIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/memes/new': {
      id: '/admin/content/memes/new'
      path: '/content/memes/new'
      fullPath: '/admin/content/memes/new'
      preLoaderRoute: typeof AdminContentMemesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/memes/$id': {
      id: '/admin/content/memes/$id'
      path: '/content/memes/$id'
      fullPath: '/admin/content/memes/$id'
      preLoaderRoute: typeof AdminContentMemesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/gallery/new': {
      id: '/admin/content/gallery/new'
      path: '/content/gallery/new'
      fullPath: '/admin/content/gallery/new'
      preLoaderRoute: typeof AdminContentGalleryNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/gallery/$id': {
      id: '/admin/content/gallery/$id'
      path: '/content/gallery/$id'
      fullPath: '/admin/content/gallery/$id'
      preLoaderRoute: typeof AdminContentGalleryIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/episodes/new': {
      id: '/admin/content/episodes/new'
      path: '/content/episodes/new'
      fullPath: '/admin/content/episodes/new'
      preLoaderRoute: typeof AdminContentEpisodesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/episodes/$id': {
      id: '/admin/content/episodes/$id'
      path: '/content/episodes/$id'
      fullPath: '/admin/content/episodes/$id'
      preLoaderRoute: typeof AdminContentEpisodesIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCharactersCharIdRoute: typeof AdminCharactersCharIdRoute
  AdminCharactersNewRoute: typeof AdminCharactersNewRoute
  AdminEventsEventIdRoute: typeof AdminEventsEventIdRoute
  AdminEventsNewRoute: typeof AdminEventsNewRoute
  AdminNewsNewsSlugRoute: typeof AdminNewsNewsSlugRoute
  AdminNewsNewRoute: typeof AdminNewsNewRoute
  AdminShopProductIdRoute: typeof AdminShopProductIdRoute
  AdminShopNewRoute: typeof AdminShopNewRoute
  AdminCharactersIndexRoute: typeof AdminCharactersIndexRoute
  AdminContentIndexRoute: typeof AdminContentIndexRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
  AdminNewsIndexRoute: typeof AdminNewsIndexRoute
  AdminShopIndexRoute: typeof AdminShopIndexRoute
  AdminContentEpisodesIdRoute: typeof AdminContentEpisodesIdRoute
  AdminContentEpisodesNewRoute: typeof AdminContentEpisodesNewRoute
  AdminContentGalleryIdRoute: typeof AdminContentGalleryIdRoute
  AdminContentGalleryNewRoute: typeof AdminContentGalleryNewRoute
  AdminContentMemesIdRoute: typeof AdminContentMemesIdRoute
  AdminContentMemesNewRoute: typeof AdminContentMemesNewRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCharactersCharIdRoute: AdminCharactersCharIdRoute,
  AdminCharactersNewRoute: AdminCharactersNewRoute,
  AdminEventsEventIdRoute: AdminEventsEventIdRoute,
  AdminEventsNewRoute: AdminEventsNewRoute,
  AdminNewsNewsSlugRoute: AdminNewsNewsSlugRoute,
  AdminNewsNewRoute: AdminNewsNewRoute,
  AdminShopProductIdRoute: AdminShopProductIdRoute,
  AdminShopNewRoute: AdminShopNewRoute,
  AdminCharactersIndexRoute: AdminCharactersIndexRoute,
  AdminContentIndexRoute: AdminContentIndexRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
  AdminNewsIndexRoute: AdminNewsIndexRoute,
  AdminShopIndexRoute: AdminShopIndexRoute,
  AdminContentEpisodesIdRoute: AdminContentEpisodesIdRoute,
  AdminContentEpisodesNewRoute: AdminContentEpisodesNewRoute,
  AdminContentGalleryIdRoute: AdminContentGalleryIdRoute,
  AdminContentGalleryNewRoute: AdminContentGalleryNewRoute,
  AdminContentMemesIdRoute: AdminContentMemesIdRoute,
  AdminContentMemesNewRoute: AdminContentMemesNewRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CommunityRouteChildren {
  CommunityPostIdRoute: typeof CommunityPostIdRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityPostIdRoute: CommunityPostIdRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface ShopRouteChildren {
  ShopProductIdRoute: typeof ShopProductIdRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopProductIdRoute: ShopProductIdRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

interface WatchRouteChildren {
  WatchEpisodeIdRoute: typeof WatchEpisodeIdRoute
}

const WatchRouteChildren: WatchRouteChildren = {
  WatchEpisodeIdRoute: WatchEpisodeIdRoute,
}

const WatchRouteWithChildren = WatchRoute._addFileChildren(WatchRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CharactersRoute: CharactersRoute,
  CommunityRoute: CommunityRouteWithChildren,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GalleryRoute: GalleryRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MemesRoute: MemesRoute,
  MyCollectionRoute: MyCollectionRoute,
  NailongVsBomboongRoute: NailongVsBomboongRoute,
  NewsRoute: NewsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ShopRoute: ShopRouteWithChildren,
  StickersRoute: StickersRoute,
  WallpapersRoute: WallpapersRoute,
  WatchRoute: WatchRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
